services:
  # Clash 配置管理器应用
  clash-config-manager:
    # 使用本地构建
    # 如需使用已构建的镜像，注释掉 build 部分，启用下面的 image 配置
    #image: clash-config-manager:latest
    container_name: clash-config-manager
    restart: unless-stopped
    
    # 本地构建配置
    build:
       context: .
       dockerfile: Dockerfile
    
    # 不映射端口到主机（通过 docker-shared-net 网络中的 Nginx 代理访问）
    # ports:
    #   - "127.0.0.1:5000:5000"
    
    # 卷挂载
    volumes:
      # 配置目录（挂载整个目录以解决文件更新问题）
      - ./config:/app/config:ro
      # 输出目录（生成的配置文件）
      - ./output:/app/output
      # 日志目录
      - ./logs:/app/logs
      # 备份目录（可选）
      - ./backups:/app/backups
    
    # 环境变量
    environment:
      # 时区设置
      - TZ=${TZ:-Asia/Shanghai}
      # 应用端口（Flask 默认端口）
      - APP_PORT=${APP_PORT:-5000}
      # 日志级别
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # 更新间隔（秒）
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-3600}
      # Webhook密钥（从配置文件读取，这里仅作为备用）
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-}
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制（可选）
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 256M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 128M
    
    # 网络配置（使用共享网络，通过 Nginx 容器代理）
    networks:
      - docker-shared-net
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# 使用外部共享网络
networks:
  docker-shared-net:
    external: true