name: Sync Config to Server

on:
  push:
    branches:
      - main
    paths:
      - 'config/rules.yaml'
      - 'config/rules.schema.json'

jobs:
  sync-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Sync configuration files
        run: |
          echo "📤 Syncing rules.yaml to server..."
          scp config/rules.yaml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/config/
          
          echo "📤 Syncing rules.schema.json to server..."
          scp config/rules.schema.json ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/config/
          
          echo "✅ Configuration files synced successfully"

      - name: Restart container
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "cd ${{ secrets.SERVER_PATH }} && docker compose restart clash-config-manager"
          
          echo "🔄 Container restarted successfully"

